### ISSUE TITLE
scriptmgr.py deprecation in non-legacy skytools?

### ISSUE THREAD

**Issue by Kallestofeles** [pgq/python-skytools#4]
First of all, greetings, thank you for all the hard work on these projects and my apologies in front if this is an incorrect place to ask these questions, alas I found no other reasonable spot.
I would like to ask whether scriptmgr.py has been deprecated in modern python-skytools implementations? I am only able to find it in the legacy-skytools package and am wondering has the functionality maybe been replaced with something different or has it been simply dropped?

Thank you and regards,
Kalle

**Comment by markokr** [comment]
Indeed, it's been dropped, overall its simpler to maintain background jobs with OS default tooling - systemctl, upstart, docker, etc.

Less complexity that way.
